### ISSUE TITLE
There seem to be only Windows Directories to browse through (while i'm on Linux?)

### ISSUE THREAD

**Issue by diorcula** [nvdweem/intellij-sqlserver-backup-restore#24]
**Describe the bug:**

When trying to restore a .bak file i am browsing through what seems to be Windows directories, but i am on linux and cannot find these directories?

**Steps to reproduce:** 

**Expected behavior:**

**Additional context:**

**Comment by nvdweem** [comment]
SQLServer restores from local files, so you are seeing the directories on the server (or in case of a Docker container, the filesystem of the container). 
To be able to move files from/to the server you could work with network shares which are connected to both the client and the server or, in case of a docker SQLServer, add a volume mapping to your local machine and work via the volume mapping.

The same will happen if you create a backup, the backup will be stored on the server. There is a workaround for the backup where the file is read into the database and then retrieved via a query so it can be downloaded to the local machine, but SQLServer doesn't allow writing files (at least not without additional privileges) so that same workaround isn't implemented for restoring a backup.

**Comment by diorcula** [comment]
Hm seems logical, i did however fixed it; it was more a stupid *did not read/think properly due to little panic attack* type of moment.

I had to copy it to the Docker Container folder and afterwards your plugin worked like a charm!!

Thanks for the extended explanation and time put in :)
