### ISSUE TITLE
Found a magical problem, the disk that appears when opening the restore menu is not the disk of the actual computer

### ISSUE THREAD

**Issue by jimlojh** [nvdweem/intellij-sqlserver-backup-restore#25]
**Describe the bug:**

Found a magical problem, the disk that appears when opening the restore menu is not the disk of the actual computer，I have four disks, but only two drive letters appear, What's even more amazing is that all the files under these two drive letters are not my local files...
**Steps to reproduce:** 

**Expected behavior:**

**Additional context:**

![(I~4 YV2$M@}WM_5` GZ3GY](https://github.com/nvdweem/intellij-sqlserver-backup-restore/assets/29743601/fa06445d-8e76-4c90-b6ea-ec24def4d27d)
![LNLAIMOUQMFB I~HS24~{YG](https://github.com/nvdweem/intellij-sqlserver-backup-restore/assets/29743601/996bebde-61a2-4704-93cc-3ea5e5b9e96a)

**Comment by nvdweem** [comment]
Apart from the folders having no name this is to be expected. SQLServer browse options are done on the database-host. Creating a backup will create a backup on the host machine, restoring a backup will restore it from the host machine disk. This is also the reason why the `Backup and download` option exists in the plugin. If the backup would already be on the client machine then there would be no need to download.
SQLServer doesn't easily allow uploading files so that's why there is no `Upload and restore` option.

Using SQLServer Management Studio to restore a backup will show the same behavior.

**Comment by 508618882** [comment]
That’s it, thank you for answering the question,Restoration can only be done on the host where SqlServer is installed.
